// Objective-C API for talking to github.com/yggdrasil-network/yggdrasil-go/src/config Go package.
//   gobind -lang=objc github.com/yggdrasil-network/yggdrasil-go/src/config
//
// File is generated by gobind. Do not edit.

#ifndef __Config_H__
#define __Config_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class ConfigMulticastInterfaceConfig;
@class ConfigNodeConfig;

@interface ConfigMulticastInterfaceConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull regex;
@property (nonatomic) BOOL beacon;
@property (nonatomic) BOOL listen;
// skipped field MulticastInterfaceConfig.Port with unsupported type: uint16

// skipped field MulticastInterfaceConfig.Priority with unsupported type: uint64

@property (nonatomic) NSString* _Nonnull password;
@end

/**
 * NodeConfig is the main configuration structure, containing configuration
options that are necessary for an Yggdrasil node to run. You will need to
supply one of these structs to the Yggdrasil core when starting a node.
 */
@interface ConfigNodeConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field NodeConfig.PrivateKey with unsupported type: github.com/yggdrasil-network/yggdrasil-go/src/config.KeyBytes

@property (nonatomic) NSString* _Nonnull privateKeyPath;
// skipped field NodeConfig.Certificate with unsupported type: *crypto/tls.Certificate

// skipped field NodeConfig.Peers with unsupported type: []string

// skipped field NodeConfig.InterfacePeers with unsupported type: map[string][]string

// skipped field NodeConfig.Listen with unsupported type: []string

@property (nonatomic) NSString* _Nonnull adminListen;
// skipped field NodeConfig.MulticastInterfaces with unsupported type: []github.com/yggdrasil-network/yggdrasil-go/src/config.MulticastInterfaceConfig

// skipped field NodeConfig.AllowedPublicKeys with unsupported type: []string

@property (nonatomic) NSString* _Nonnull groupPassword;
@property (nonatomic) NSString* _Nonnull ifName;
// skipped field NodeConfig.IfMTU with unsupported type: uint64

@property (nonatomic) BOOL logLookups;
@property (nonatomic) BOOL nodeInfoPrivacy;
// skipped field NodeConfig.NodeInfo with unsupported type: map[string]interface{}

- (BOOL)generateSelfSignedCertificate:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)marshalPEMCertificate:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)marshalPEMPrivateKey:(NSError* _Nullable* _Nullable)error;
- (void)newPrivateKey;
// skipped method NodeConfig.ReadFrom with unsupported parameter or return types

- (BOOL)unmarshalHJSON:(NSData* _Nullable)b error:(NSError* _Nullable* _Nullable)error;
- (BOOL)unmarshalPEMPrivateKey:(NSData* _Nullable)b error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Generates default configuration and returns a pointer to the resulting
NodeConfig. This is used when outputting the -genconf parameter and also when
using -autoconf.
 */
FOUNDATION_EXPORT ConfigNodeConfig* _Nullable ConfigGenerateConfig(void);

#endif
