// Objective-C API for talking to github.com/yggdrasil-network/yggdrasil-go/contrib/mobile Go package.
//   gobind -lang=objc github.com/yggdrasil-network/yggdrasil-go/contrib/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Config.objc.h"

@class MobileConfigSummary;
@class MobileMobileLogger;
@class MobileYggdrasil;

@interface MobileConfigSummary : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull publicKey;
@property (nonatomic) NSString* _Nonnull iPv6Address;
@property (nonatomic) NSString* _Nonnull iPv6Subnet;
@end

@interface MobileMobileLogger : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Yggdrasil mobile package is meant to "plug the gap" for mobile support, as
Gomobile will not create headers for Swift/Obj-C etc if they have complex
(non-native) types. Therefore for iOS we will expose some nice simple
functions. Note that in the case of iOS we handle reading/writing to/from TUN
in Swift therefore we use the "dummy" TUN interface instead.
 */
@interface MobileYggdrasil : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * GetAddressString gets the node's IPv6 address
 */
- (NSString* _Nonnull)getAddressString;
/**
 * GetMTU returns the configured node MTU. This must be called AFTER Start.
 */
- (long)getMTU;
- (NSString* _Nonnull)getPathsJSON;
- (NSString* _Nonnull)getPeersJSON;
/**
 * GetPublicKeyString gets the node's public key in hex form
 */
- (NSString* _Nonnull)getPublicKeyString;
/**
 * GetRoutingEntries gets the number of entries in the routing table
 */
- (long)getRoutingEntries;
/**
 * GetSubnetString gets the node's IPv6 subnet in CIDR notation
 */
- (NSString* _Nonnull)getSubnetString;
- (NSString* _Nonnull)getTreeJSON;
/**
 * Recv waits for and reads a packet coming from Yggdrasil. It
will be a fully formed IPv6 packet
 */
- (NSData* _Nullable)recv:(NSError* _Nullable* _Nullable)error;
/**
 * Recv waits for and reads a packet coming from Yggdrasil to given buffer, returning size of packet
 */
- (BOOL)recvBuffer:(NSData* _Nullable)buf ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * Retry resets the peer connection timer and tries to dial them immediately.
 */
- (void)retryPeersNow;
/**
 * Send sends a packet to Yggdrasil. It should be a fully formed
IPv6 packet
 */
- (BOOL)send:(NSData* _Nullable)p0 error:(NSError* _Nullable* _Nullable)error;
/**
 * Send sends a packet from given buffer to Yggdrasil. From first byte up to length.
 */
- (BOOL)sendBuffer:(NSData* _Nullable)p0 length:(long)length error:(NSError* _Nullable* _Nullable)error;
/**
 * StartAutoconfigure starts a node with a randomly generated config
 */
- (BOOL)startAutoconfigure:(NSError* _Nullable* _Nullable)error;
/**
 * StartJSON starts a node with the given JSON config. You can get JSON config
(rather than HJSON) by using the GenerateConfigJSON() function
 */
- (BOOL)startJSON:(NSData* _Nullable)configjson error:(NSError* _Nullable* _Nullable)error;
/**
 * Stop the mobile Yggdrasil instance
 */
- (BOOL)stop:(NSError* _Nullable* _Nullable)error;
- (BOOL)takeOverTUN:(int32_t)fd error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * GenerateConfigJSON generates mobile-friendly configuration in JSON format
 */
FOUNDATION_EXPORT NSData* _Nullable MobileGenerateConfigJSON(void);

FOUNDATION_EXPORT NSString* _Nonnull MobileGetVersion(void);

FOUNDATION_EXPORT MobileConfigSummary* _Nullable MobileSummaryForConfig(NSData* _Nullable b);

#endif
